### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by lishewen** [JohnWong/bus-minigram#3]
```js
   wx.request({
      url: 'https://restapi.amap.com/v3/bus/lineid?key=248138cabdb96b4743038bcad349b000&output=json&city=%E6%9D%AD%E5%B7%9E&id=' + this.routeId,
```
中的routeId如何获得，高德地图中的开发文档好像也没有提到

**Comment by lishewen** [comment]
另外想咨询下地图模式下如何把车辆实时显示在地图上

**Comment by JohnWong** [comment]
这我也不是很清楚，只是用到的数据源那里拿到的就是高德的id。也可以高德地图网页版抓包看看接口的信息。车辆显示我这里做了，要实时推送是不可能的，即使定时刷吧

**Comment by lishewen** [comment]
感谢，我已经接上我们当地的数据了
![image](https://user-images.githubusercontent.com/837067/35308404-8e05410e-00e2-11e8-8059-e68a3248481c.png)
![image](https://user-images.githubusercontent.com/837067/35308437-b042a5ea-00e2-11e8-8e1b-3bdb346664ed.png)
另外还想问个问题，地图页面中当前站点的marker是有个气泡显示的，在开发者工具那里可以看到，但在手机上预览却没用，换成点击模式 'BYCLICK' 点击也是没有反映的，这个一般会是什么问题？

**Comment by JohnWong** [comment]
@lishewen 这个只是我花了几天时间做个东西玩，并没有对小程序有很深的了解。类似这样的问题去小程序相关的地方找找吧。另外这个界面是照着车来了做的，如果商用请当心。
