### ISSUE TITLE
想问一下公交的api用的是什么，能实时看公交车的位置吗

### ISSUE THREAD

**Issue by xvjialing** [JohnWong/bus-minigram#4]

**Comment by JohnWong** [comment]
你好。api使用的是车来了的，没有公开的资料，抓包看的。说不定哪天就被封了无法使用了。不是非常及时，因为公交上报有一点延迟，服务端没有推送，需要客户端自行刷，以前感觉大概是一分钟的延迟吧。数据里好像有公交车的经纬度，记不太清了很久没维护了

**Comment by xvjialing** [comment]
是的，现在小程序已经看不到数据了
